 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comentarios", type: :request do
  # Comentario. As you add validations to Comentario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Comentario.create! valid_attributes
      get comentarios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      comentario = Comentario.create! valid_attributes
      get comentario_url(comentario)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_comentario_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      comentario = Comentario.create! valid_attributes
      get edit_comentario_url(comentario)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Comentario" do
        expect {
          post comentarios_url, params: { comentario: valid_attributes }
        }.to change(Comentario, :count).by(1)
      end

      it "redirects to the created comentario" do
        post comentarios_url, params: { comentario: valid_attributes }
        expect(response).to redirect_to(comentario_url(Comentario.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Comentario" do
        expect {
          post comentarios_url, params: { comentario: invalid_attributes }
        }.to change(Comentario, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post comentarios_url, params: { comentario: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested comentario" do
        comentario = Comentario.create! valid_attributes
        patch comentario_url(comentario), params: { comentario: new_attributes }
        comentario.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the comentario" do
        comentario = Comentario.create! valid_attributes
        patch comentario_url(comentario), params: { comentario: new_attributes }
        comentario.reload
        expect(response).to redirect_to(comentario_url(comentario))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        comentario = Comentario.create! valid_attributes
        patch comentario_url(comentario), params: { comentario: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested comentario" do
      comentario = Comentario.create! valid_attributes
      expect {
        delete comentario_url(comentario)
      }.to change(Comentario, :count).by(-1)
    end

    it "redirects to the comentarios list" do
      comentario = Comentario.create! valid_attributes
      delete comentario_url(comentario)
      expect(response).to redirect_to(comentarios_url)
    end
  end
end
