 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/relacionamentos", type: :request do
  # Relacionamento. As you add validations to Relacionamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Relacionamento.create! valid_attributes
      get relacionamentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      relacionamento = Relacionamento.create! valid_attributes
      get relacionamento_url(relacionamento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_relacionamento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      relacionamento = Relacionamento.create! valid_attributes
      get edit_relacionamento_url(relacionamento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Relacionamento" do
        expect {
          post relacionamentos_url, params: { relacionamento: valid_attributes }
        }.to change(Relacionamento, :count).by(1)
      end

      it "redirects to the created relacionamento" do
        post relacionamentos_url, params: { relacionamento: valid_attributes }
        expect(response).to redirect_to(relacionamento_url(Relacionamento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Relacionamento" do
        expect {
          post relacionamentos_url, params: { relacionamento: invalid_attributes }
        }.to change(Relacionamento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post relacionamentos_url, params: { relacionamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested relacionamento" do
        relacionamento = Relacionamento.create! valid_attributes
        patch relacionamento_url(relacionamento), params: { relacionamento: new_attributes }
        relacionamento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the relacionamento" do
        relacionamento = Relacionamento.create! valid_attributes
        patch relacionamento_url(relacionamento), params: { relacionamento: new_attributes }
        relacionamento.reload
        expect(response).to redirect_to(relacionamento_url(relacionamento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        relacionamento = Relacionamento.create! valid_attributes
        patch relacionamento_url(relacionamento), params: { relacionamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested relacionamento" do
      relacionamento = Relacionamento.create! valid_attributes
      expect {
        delete relacionamento_url(relacionamento)
      }.to change(Relacionamento, :count).by(-1)
    end

    it "redirects to the relacionamentos list" do
      relacionamento = Relacionamento.create! valid_attributes
      delete relacionamento_url(relacionamento)
      expect(response).to redirect_to(relacionamentos_url)
    end
  end
end
